services:
  postgres:
    image: postgres:15-alpine
    container_name: uas-pengweb-db
    environment:
      POSTGRES_DB: uas_pengweb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pyramid-backend:
    build: .
    container_name: uas-pyramid-backend
    ports:
      - "6543:6543"
    environment:
      DATABASE_URL: postgresql+psycopg2://app_prod_user:12345@postgres:5432/uas_pengweb
      PYTHONUNBUFFERED: 1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./storage:/app/storage
      - .:/app
    command: sh -c "alembic upgrade head && python main.py"

volumes:
  postgres_data:
